export type Product = {
  id: string;
  name: string;
  tagline: string;
  description: string;
  category:
    | "Business"
    | "Family"
    | "Lifestyle"
    | "Education"
    | "Health"
    | "Travel"
    | "Finance"
    | "Productivity"
    | "Media"
    | "Creative"
    | "AI"
    | "Commerce"
    | "DevTools"
    | "Security"
    | "HR"
    | "Agritech"
    | "Logistics"
    | "Events"
    | "IoT";
  status: "Live" | "Beta" | "Coming Soon";
  accent: string; // hex tone used for hover gradient
  image: string;
  metric?: { label: string; value: string };
  /**
   * External product URL (e.g. live marketing/app site). When set, the
   * product card and bottom-dock pill navigate here instead of scrolling
   * to the in-page anchor.
   */
  url?: string;
};

// Local image paths — generated by `npm run build-images` from picsum sources.
// Checked into git so the live site never depends on a third-party CDN.
const img = (seed: string) => `/img/products/${seed}.webp`;

export const PRODUCTS: Product[] = [
  {
    id: "pravah",
    name: "Pravah",
    tagline: "India-first CRM that flows with your sales",
    description:
      "Multilingual pipelines, WhatsApp-native conversations, and GST-aware quoting for ambitious teams across Bharat.",
    category: "Business",
    status: "Live",
    accent: "#f59e0b",
    image: img("pravah-crm"),
    metric: { label: "Pipeline lift", value: "+38%" },
    url: "https://pravah.mishtilabs.com/",
  },
  {
    id: "flowlife",
    name: "FlowLife",
    tagline: "Your money and time, in flow",
    description:
      "A unified personal finance and productivity app. Track expenses, manage tasks, split bills with friends, and see how your money and time connect.",
    category: "Finance",
    status: "Live",
    accent: "#6366f1",
    image: img("flowlife-finance"),
    url: "https://flowlife.mishtilabs.com/",
  },
  {
    id: "growright",
    name: "GrowRight",
    tagline: "A gentle companion for new parents",
    description:
      "Milestone tracking, pediatrician-vetted guides, sleep windows and a supportive parent circle — without the noise.",
    category: "Family",
    status: "Coming Soon",
    accent: "#ff5c8a",
    image: img("growright-baby"),
    metric: { label: "Happy parents", value: "120k" },
  },
  {
    id: "weddingverse",
    name: "WeddingVerse",
    tagline: "Plan a wedding the way you imagined it",
    description:
      "End-to-end planning suite for couples and professional planners — vendors, RSVPs, rituals, and a beautiful timeline.",
    category: "Lifestyle",
    status: "Coming Soon",
    accent: "#be185d",
    image: img("wedding-mandap"),
    metric: { label: "Weddings powered", value: "8,400+" },
  },
  {
    id: "mehfil",
    name: "Mehfil",
    tagline: "Ticketing for unforgettable gatherings",
    description:
      "Sell tickets, run waitlists and stream after-movies. Built for organizers who care about the room.",
    category: "Events",
    status: "Coming Soon",
    accent: "#a855f7",
    image: img("mehfil-events"),
    metric: { label: "Tickets/min", value: "12k" },
  },
  {
    id: "kirana-cloud",
    name: "Kirana Cloud",
    tagline: "POS for the corner store, supercharged",
    description:
      "Inventory, billing, khata, and UPI — all from a phone. Works offline-first for the messiest of bandwidth.",
    category: "Commerce",
    status: "Coming Soon",
    accent: "#16a34a",
    image: img("kirana-store"),
    metric: { label: "Stores live", value: "26,500" },
  },
  {
    id: "vidya-ai",
    name: "Vidya AI",
    tagline: "Adaptive learning that meets every learner",
    description:
      "Personalized lesson paths, Socratic tutors, and rubric-based feedback for K-12 and beyond.",
    category: "Education",
    status: "Coming Soon",
    accent: "#22d3ee",
    image: img("vidya-classroom"),
    metric: { label: "Avg. score lift", value: "+27%" },
  },
  {
    id: "vaidya",
    name: "Vaidya",
    tagline: "Telemedicine that feels human",
    description:
      "Triage, prescriptions, lab follow-ups and ABDM-ready records. Privacy is the default, not an upsell.",
    category: "Health",
    status: "Coming Soon",
    accent: "#0891b2",
    image: img("vaidya-health"),
    metric: { label: "Consults/day", value: "9,200" },
  },
  {
    id: "annapurna",
    name: "Annapurna",
    tagline: "Restaurant OS that respects the kitchen",
    description:
      "KOT-aware POS, recipe costing, swiggy/zomato sync, and a captain app that doesn't get in the way.",
    category: "Commerce",
    status: "Coming Soon",
    accent: "#d97706",
    image: img("annapurna-food"),
    metric: { label: "Tables flipped", value: "+22%" },
  },
  {
    id: "paribar",
    name: "Paribar",
    tagline: "Family stories, beautifully kept",
    description:
      "Build a family tree, keep heirloom photos and voice memories, and pass them down for generations.",
    category: "Family",
    status: "Coming Soon",
    accent: "#ef4444",
    image: img("paribar-family"),
  },
  {
    id: "yatra-os",
    name: "Yatra OS",
    tagline: "Itineraries that adapt as you wander",
    description:
      "AI co-planner with realtime rebooking, offline maps and group voting on what to do tonight.",
    category: "Travel",
    status: "Coming Soon",
    accent: "#0ea5e9",
    image: img("yatra-travel"),
    metric: { label: "Trips planned", value: "1.4M" },
  },
  {
    id: "mandi-pulse",
    name: "Mandi Pulse",
    tagline: "Realtime mandi prices for farmers",
    description:
      "Crop-grade aware pricing, predictions, and direct buyer connect. SMS first, app second.",
    category: "Agritech",
    status: "Coming Soon",
    accent: "#84cc16",
    image: img("mandi-farm"),
    metric: { label: "Mandis live", value: "1,800" },
  },
  {
    id: "lekha",
    name: "Lekha",
    tagline: "Invoicing for freelancers, done right",
    description:
      "Recurring invoices, multi-currency, GST/VAT, payment links, and gentle reminders that get paid.",
    category: "Finance",
    status: "Coming Soon",
    accent: "#10b981",
    image: img("lekha-invoice"),
    metric: { label: "Paid 14 days faster", value: "avg." },
  },
  {
    id: "sangrah",
    name: "Sangrah",
    tagline: "A vault for your team's knowledge",
    description:
      "End-to-end encrypted documents, policy docs and SOPs with semantic search and audit trails.",
    category: "Productivity",
    status: "Coming Soon",
    accent: "#6366f1",
    image: img("sangrah-vault"),
  },
  {
    id: "dhwani",
    name: "Dhwani",
    tagline: "Podcast hosting with cinematic analytics",
    description:
      "Lossless hosting, dynamic ad insertion and a studio-grade editor. Made for serious storytellers.",
    category: "Media",
    status: "Coming Soon",
    accent: "#8b5cf6",
    image: img("dhwani-podcast"),
    metric: { label: "Listens", value: "92M" },
  },
  {
    id: "roshni",
    name: "Roshni",
    tagline: "A warm dashboard for your smart home",
    description:
      "Routines that respect your circadian rhythm, energy insights, and Matter-native pairing.",
    category: "IoT",
    status: "Coming Soon",
    accent: "#f97316",
    image: img("roshni-home"),
  },
  {
    id: "chitra",
    name: "Chitra",
    tagline: "AI photo studio for every brand",
    description:
      "Product photoshoots, on-model imagery, and brand-consistent campaigns in minutes.",
    category: "Creative",
    status: "Coming Soon",
    accent: "#ec4899",
    image: img("chitra-photos"),
    metric: { label: "Shots/sec", value: "240" },
  },
  {
    id: "charcha",
    name: "Charcha",
    tagline: "Async chat for thoughtful teams",
    description:
      "Threads that don't drown you, recap digests, and a calmer way to work across timezones.",
    category: "Productivity",
    status: "Coming Soon",
    accent: "#3b82f6",
    image: img("charcha-team"),
  },
  {
    id: "bandhan",
    name: "Bandhan",
    tagline: "HR & payroll your team will love",
    description:
      "Onboarding flows, leaves, payroll, and a culture wall that actually celebrates people.",
    category: "HR",
    status: "Coming Soon",
    accent: "#f43f5e",
    image: img("bandhan-hr"),
    metric: { label: "On-time payroll", value: "100%" },
  },
  {
    id: "niyam",
    name: "Niyam",
    tagline: "Compliance, made human",
    description:
      "Contract review, policy templates and ROC filings — assisted by domain-trained AI agents.",
    category: "Business",
    status: "Coming Soon",
    accent: "#0d9488",
    image: img("niyam-legal"),
  },
  {
    id: "sahaj",
    name: "Sahaj",
    tagline: "A no-code studio for builders",
    description:
      "Visual workflows, real databases, and the ability to eject to typed code when you outgrow it.",
    category: "DevTools",
    status: "Coming Soon",
    accent: "#14b8a6",
    image: img("sahaj-build"),
  },
  {
    id: "tarang",
    name: "Tarang",
    tagline: "Live sports scoring & broadcast",
    description:
      "Ball-by-ball cricket, multi-cam streaming, fantasy hooks, and a fan wall that pops.",
    category: "Media",
    status: "Coming Soon",
    accent: "#22c55e",
    image: img("tarang-sports"),
    metric: { label: "Concurrent fans", value: "3.1M" },
  },
  {
    id: "drishti",
    name: "Drishti",
    tagline: "Computer vision APIs for builders",
    description:
      "OCR, object detection, KYC, and crowd analytics — production-ready models with a kind pricing curve.",
    category: "AI",
    status: "Coming Soon",
    accent: "#06b6d4",
    image: img("drishti-vision"),
  },
  {
    id: "vimaan",
    name: "Vimaan",
    tagline: "Logistics tracking that just works",
    description:
      "Last-mile to long-haul, driver-friendly app, fuel and toll insights, and proof-of-delivery.",
    category: "Logistics",
    status: "Coming Soon",
    accent: "#eab308",
    image: img("vimaan-logistics"),
  },
  {
    id: "kavya",
    name: "Kavya",
    tagline: "A writers' workspace for serious words",
    description:
      "Drafts, references, citations, and a focus mode that the page itself protects.",
    category: "Creative",
    status: "Coming Soon",
    accent: "#a78bfa",
    image: img("kavya-writers"),
  },
  {
    id: "mela",
    name: "Mela",
    tagline: "Hyperlocal marketplace for every neighborhood",
    description:
      "Discover artisans and home kitchens nearby, with same-day delivery and zero predatory ads.",
    category: "Commerce",
    status: "Coming Soon",
    accent: "#fb7185",
    image: img("mela-market"),
    metric: { label: "Sellers", value: "48k" },
  },
  {
    id: "suraksha",
    name: "Suraksha",
    tagline: "Cybersecurity dashboard for SMBs",
    description:
      "EDR, phishing drills, posture scoring, and friendly remediation playbooks. Security without the jargon.",
    category: "Security",
    status: "Coming Soon",
    accent: "#dc2626",
    image: img("suraksha-secure"),
  },
  {
    id: "shilp",
    name: "Shilp",
    tagline: "Portfolio builder for designers & studios",
    description:
      "Editorial-grade case studies, client-only previews and motion-aware galleries that breathe.",
    category: "Creative",
    status: "Coming Soon",
    accent: "#ea580c",
    image: img("shilp-portfolio"),
  },
];

export const CATEGORIES = Array.from(
  new Set(PRODUCTS.map((p) => p.category)),
).sort();
